version: '3'
services:
  client:
    image: "swich313/multi-client"
    deploy:
      resources:
        limits:
          memory: 128m
#   mem_limit: 128m
    hostname: client
  server:
    image: swich313/multi-server
    deploy:
      resources:
        limits:
          memory: 128m
#   mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: swich313/multi-worker
    deploy:
      resources:
        limits:
          memory: 128m
#   mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: swich313/multi-nginx
    deploy:
      resources:
        limits:
          memory: 128m
#   mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
